Repository modrinth/labrinth, pull requests merged in 2020-07, with the labels that each got.

#32 Backblaze Driver
  .env
  .github/workflows/tests.yml
  .idea/.gitignore
  .idea/dataSources.xml
  .idea/deployment.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jsLibraryMappings.xml
  .idea/labrinth.iml
  .idea/modules.xml
  .idea/sqldialects.xml
  Cargo.toml
  src/file_hosting/authorization.rs
  src/file_hosting/delete.rs
  src/file_hosting/mod.rs
  src/file_hosting/upload.rs
  src/main.rs
  src/routes/index.rs
  src/search/indexing/curseforge_import.rs
  src/search/indexing/local_import.rs
  src/search/indexing/mod.rs
Labels: Namespace: Miscellaneous, Priority: High, Status: Review Ready

#42 fix/ci: Fix build matrix
  .github/labels.yml
  .github/workflows/tests.yml
Labels: Meta: BugFix, Meta: Cleanup, Meta: Maintenance, Namespace: Project, Priority: Critical, Status: Ready To Merge

#43 fix: quote the numbers on the github label
  .github/labels.yml
Labels: Meta: BugFix, Meta: Cleanup, Meta: Maintenance, Namespace: Project, Priority: Low, Status: Review Ready
